version: '3'

services:
  auth-service:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - DYNAMODB_TABLE_USERS=${DYNAMODB_TABLE_USERS}
    volumes:
      - ./src:/usr/src/app/src
    restart: unless-stopped

  # Si deseas ejecutar DynamoDB localmente para desarrollo
  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    restart: unless-stopped

volumes:
  dynamodb-data: